task: openwebtext_perplexity
dataset_path: skylion007/openwebtext
dataset_kwargs:
  trust_remote_code: true
test_split: train
output_type: loglikelihood_rolling
doc_to_text: "text"
doc_to_target: "text"
metric_list:
  - metric: word_perplexity
  - metric: byte_perplexity
  - metric: bits_per_byte
metadata:
  version: 1.0