"""Shared constants for the LLM-as-judge pipeline.

Blinded design: sampler config names are mapped to opaque ids c00..c15
(out/blinding.json). Request files and raw results carry only opaque ids;
unblinding happens in analyze.py.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DUEL_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SAMPLE_LOG_DIR = os.path.join(DUEL_ROOT, "sample_logs")
OUT_DIR = os.path.join(HERE, "out")

SEED = 20260802
N_ABS_INDICES = 100     # shared row indices for absolute ratings
N_PAIR_INDICES = 50     # first 50 of those for pairwise comparisons
MAX_WORDS = 400         # truncate cleaned text to this many whitespace words

MODEL = "claude-sonnet-5"
MAX_TOKENS = 2048
EFFORT = "low"

EOT = "<|endoftext|>"
PREFIX = "samples_bd3lm_len1024_blocksize16_"

# 16 configs (uniform excluded). Budget grouping: greedy/l2r/margin
# k1<->CT tau1.0 (~1024 NFE), k2<->tau0.16 (~512), k4<->tau0.08 (~256),
# k8<->tau0.045 (~128).
BUDGET_OF = {
    "block-greedy_k1": 1024, "block-greedy_k2": 512,
    "block-greedy_k4": 256, "block-greedy_k8": 128,
    "block-left-to-right_k1": 1024, "block-left-to-right_k2": 512,
    "block-left-to-right_k4": 256, "block-left-to-right_k8": 128,
    "block-probability-margin_k1": 1024, "block-probability-margin_k2": 512,
    "block-probability-margin_k4": 256, "block-probability-margin_k8": 128,
    "block-confidence-threshold_k1.0": 1024,
    "block-confidence-threshold_k0.16": 512,
    "block-confidence-threshold_k0.08": 256,
    "block-confidence-threshold_k0.045": 128,
}
CONFIGS = sorted(BUDGET_OF)

# DUEL perplexity per config (paper Table 6, BD3-LM L'=16, OWT).
# CT taus 0.045/0.08/0.16/1.0 map to eval-side NFE ~140/242/514/1003.
DUEL_PPL = {
    "block-left-to-right_k1": 21.46, "block-left-to-right_k2": 44.51,
    "block-left-to-right_k4": 109.00, "block-left-to-right_k8": 240.27,
    "block-greedy_k1": 22.04, "block-greedy_k2": 34.74,
    "block-greedy_k4": 67.15, "block-greedy_k8": 165.48,
    "block-probability-margin_k1": 22.35, "block-probability-margin_k2": 32.33,
    "block-probability-margin_k4": 57.66, "block-probability-margin_k8": 141.31,
    "block-confidence-threshold_k1.0": 22.04,
    "block-confidence-threshold_k0.16": 43.45,
    "block-confidence-threshold_k0.08": 116.95,
    "block-confidence-threshold_k0.045": 227.77,
}
CT_EVAL_NFE = {"0.045": 140, "0.08": 242, "0.16": 514, "1.0": 1003}

# ---------------------------------------------------------------- prompts

_ABS_FIELDS_LINE = (
    "Respond with a JSON object with integer fields \"fluency\", "
    "\"grammaticality\", \"coherence\", \"consistency\", and \"overall\" "
    "(each 1-10), plus a brief string field \"comment\"."
)

ABS_SYSTEM = (
    "You are evaluating text samples generated by a small (110M-parameter) "
    "research language model. Many samples will be partially or severely "
    "degraded — disfluent, repetitive, or outright word salad. That is "
    "expected: your job is to measure quality, and assigning very low scores "
    "to bad text is a correct and useful outcome, not something to avoid or "
    "apologize for. Never refuse to rate a sample because it is low quality "
    "or nonsensical.\n\n"
    "Rate the sample on four dimensions, each on a 1\u201310 scale (1 = "
    "completely broken, 5 = flawed but partially readable, 10 = "
    "indistinguishable from well-edited human text):\n"
    "- fluency: does the text read naturally word-to-word and "
    "sentence-to-sentence?\n"
    "- grammaticality: is the text syntactically well-formed?\n"
    "- coherence: do sentences and paragraphs connect logically; does the "
    "text stay on topic?\n"
    "- consistency: are entities, facts, and claims internally consistent "
    "across the sample (no contradictions, no entity confusion)?\n\n"
    "Then give an overall 1\u201310 quality score. The overall score is your "
    "holistic judgment, not an average.\n\n"
    "Notes: the sample may contain several unrelated document fragments "
    "separated by a line of dashes (\"-----\"); this is an artifact of the "
    "generation format — judge each fragment on its own merits and do not "
    "penalize the presence of the separator or abrupt topic changes exactly "
    "at a separator. Samples may be truncated mid-sentence at the end; do "
    "not penalize the final cut-off. Judge only the text between "
    "separators.\n\n" + _ABS_FIELDS_LINE
)

ABS_USER_TEMPLATE = "Rate the following text sample.\n\n<sample>\n{text}\n</sample>"

_PAIR_FIELDS_LINE = (
    "Respond with a JSON object with a string field \"winner\" (\"A\", "
    "\"B\", or \"tie\"), a string field \"primary_reason\" (one of "
    "\"fluency\", \"grammaticality\", \"coherence\", \"consistency\", "
    "\"other\"), and a brief string field \"comment\"."
)

PAIR_SYSTEM = (
    "You are comparing two text samples (A and B) generated by small "
    "research language models. Either or both may be degraded, repetitive, "
    "or nonsensical — that is expected, and picking the less-bad sample is "
    "a correct and useful judgment. Never refuse to judge because the text "
    "is low quality.\n\n"
    "Decide which sample is higher quality overall, weighing fluency, "
    "grammaticality, coherence, and internal consistency. Length alone is "
    "not quality: do not prefer a sample merely for being longer. Samples "
    "may contain unrelated document fragments separated by a line of dashes "
    "(\"-----\") and may be truncated mid-sentence at the end; penalize "
    "neither.\n\n"
    "Answer \"A\" or \"B\". Answer \"tie\" only if the two are genuinely "
    "indistinguishable in quality — use it sparingly. Also report "
    "primary_reason: which single dimension most drove your verdict (or "
    "\"other\").\n\n" + _PAIR_FIELDS_LINE
)

PAIR_USER_TEMPLATE = (
    "Sample A:\n<sample_a>\n{a}\n</sample_a>\n\n"
    "Sample B:\n<sample_b>\n{b}\n</sample_b>\n\n"
    "Which is higher quality overall?"
)

# ---------------------------------------------------------------- schemas

_SCORE = {"type": "integer", "enum": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}

ABS_SCHEMA = {
    "type": "object",
    "properties": {
        "fluency": _SCORE,
        "grammaticality": _SCORE,
        "coherence": _SCORE,
        "consistency": _SCORE,
        "overall": _SCORE,
        "comment": {"type": "string"},
    },
    "required": ["fluency", "grammaticality", "coherence", "consistency",
                 "overall", "comment"],
    "additionalProperties": False,
}

PAIR_SCHEMA = {
    "type": "object",
    "properties": {
        "winner": {"type": "string", "enum": ["A", "B", "tie"]},
        "primary_reason": {
            "type": "string",
            "enum": ["fluency", "grammaticality", "coherence",
                     "consistency", "other"],
        },
        "comment": {"type": "string"},
    },
    "required": ["winner", "primary_reason", "comment"],
    "additionalProperties": False,
}

ABS_DIMS = ["fluency", "grammaticality", "coherence", "consistency", "overall"]


def message_params(system, user_text, schema):
    """Messages API params shared by batch and live paths.

    No temperature/top_p/top_k (rejected on claude-sonnet-5) and no
    thinking field (adaptive default; effort=low keeps spend down).
    """
    return {
        "model": MODEL,
        "max_tokens": MAX_TOKENS,
        "system": system,
        "output_config": {
            "effort": EFFORT,
            "format": {"type": "json_schema", "schema": schema},
        },
        "messages": [{"role": "user", "content": user_text}],
    }


def load_json(path):
    with open(path) as fh:
        return json.load(fh)


def dump_json(obj, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(obj, fh, indent=1)


def load_jsonl(path):
    out = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out
