"""Wall-clock cost of GENERATION for the sampler-comparison arms.

Companion to scripts/cost_decomposition.py, which timed only the *evaluation* of
pre-existing samples. All three metrics (DUEL, gen-ppl, MAUVE) require samples to
exist first, so a fair cost table needs generation folded in.

Protocol is taken verbatim from scripts/sampler_comparison/gen_ppl.sh:
  loader.eval_batch_size=1, sampling.num_sample_batches=1000, sampling.nucleus_p=0.9,
  algo.T=5000, block_size=16, model.length=1024, kv_cache=true, seed=2,
  ckpt=kuleshov-group/bd3lm-owt-block_size16, attn_backend=sdpa.

Full 1000-sample generation at eval_batch_size=1 is ~1.5 h per arm, so this times a
SUBSET of N samples per arm and reports mean +- sd per sample. Extrapolation to 1000
is done by the caller/report, never silently here: the JSON carries per-sample times.

Each sample is generated by a separate _sample(num_sample_batches=1) call, timed with
torch.cuda.synchronize() on both sides, after a discarded warmup sample.

Usage:
  python scripts/generation_timing.py --strategy block_greedy --k 1 --n 50 \
      --out results/generation_timing/greedy_k1.json
"""

import argparse
import json
import os
import statistics
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import torch


def _sync():
    if torch.cuda.is_available():
        torch.cuda.synchronize()


def co_tenants():
    """Record other processes on GPU 0 so contention is auditable."""
    try:
        out = subprocess.run(
            ['nvidia-smi', '--query-compute-apps=pid,used_memory',
             '--format=csv,noheader'],
            capture_output=True, text=True, timeout=30).stdout.strip()
        return [l for l in out.splitlines() if l.strip()]
    except Exception as e:  # noqa: BLE001
        return [f'<nvidia-smi failed: {e}>']


def build_config(strategy, k, seqlen, block_size, ckpt):
    from hydra import compose, initialize_config_dir

    cfg_dir = os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), 'configs')
    overrides = [
        'loader.eval_batch_size=1',
        'model=small',
        'algo=bd3lm',
        'algo.T=5000',
        'algo.backbone=hf_dit',
        'data=openwebtext-split',
        f'model.length={seqlen}',
        f'block_size={block_size}',
        'mode=sample_eval',
        f'eval.checkpoint_path={ckpt}',
        'model.attn_backend=sdpa',
        'seed=2',
        'sampling.num_sample_batches=1',   # one sample per _sample() call
        'sampling.nucleus_p=0.9',
        'sampling.kv_cache=true',
    ]
    if strategy != 'uniform':
        overrides += [f'+sampling.strategy={strategy}', f'+sampling.strategy_k={k}']
    with initialize_config_dir(config_dir=cfg_dir, version_base=None):
        return compose(config_name='config', overrides=overrides)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--strategy', default='block_greedy')
    ap.add_argument('--k', default='1')
    ap.add_argument('--n', type=int, default=50, help='timed samples')
    ap.add_argument('--warmup', type=int, default=2)
    ap.add_argument('--seqlen', type=int, default=1024)
    ap.add_argument('--block-size', type=int, default=16)
    ap.add_argument('--ckpt', default='kuleshov-group/bd3lm-owt-block_size16')
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    k = float(args.k) if '.' in str(args.k) else int(args.k)

    import dataloader
    import diffusion

    cfg = build_config(args.strategy, k, args.seqlen, args.block_size, args.ckpt)
    tokenizer = dataloader.get_tokenizer(cfg)

    meta = {
        'strategy': args.strategy, 'k': k, 'n_timed': args.n,
        'seqlen': args.seqlen, 'block_size': args.block_size,
        'eval_batch_size': 1, 'nucleus_p': 0.9,
        'gpu': torch.cuda.get_device_name(0) if torch.cuda.is_available() else None,
        'node': os.environ.get('SLURMD_NODENAME'),
        'job_id': os.environ.get('SLURM_JOB_ID'),
        'exclusive': os.environ.get('SLURM_JOB_EXCLUSIVE'),
        'pytorch_cuda_alloc_conf': os.environ.get('PYTORCH_CUDA_ALLOC_CONF'),
        'co_tenants_at_start': co_tenants(),
    }
    print(f'[info] node={meta["node"]} gpu={meta["gpu"]}', flush=True)
    print(f'[info] co-tenants at start: {meta["co_tenants_at_start"]}', flush=True)

    t0 = time.perf_counter()
    model = diffusion.Diffusion(cfg, tokenizer=tokenizer)
    model = model.to('cuda')
    _sync()
    meta['model_load_s'] = time.perf_counter() - t0
    print(f'[timing] model_load {meta["model_load_s"]:.2f} s', flush=True)

    # Mirror restore_model_and_sample()'s pre-sampling setup (diffusion.py:1317-1325)
    if model.ema:
        model.ema.store(model._get_parameters())
        model.ema.copy_to(model._get_parameters())
    model.backbone.eval()
    model.noise.eval()

    def one_sample():
        _sync()
        t = time.perf_counter()
        out = model._sample(seqlen=args.seqlen, num_steps=cfg.algo.T,
                            batch_size_per_gpu=1)
        _sync()
        return time.perf_counter() - t, out

    for i in range(args.warmup):
        dt, _ = one_sample()
        print(f'[warmup {i}] {dt:.3f} s (discarded)', flush=True)

    times = []
    torch.cuda.reset_peak_memory_stats()
    for i in range(args.n):
        dt, _ = one_sample()
        times.append(dt)
        if (i + 1) % 5 == 0 or i == 0:
            print(f'[sample {i+1}/{args.n}] {dt:.3f} s  '
                  f'running_mean={statistics.mean(times):.3f}', flush=True)

    nfes = list(model.metrics.gen_nfes)[-args.n:]
    mean = statistics.mean(times)
    sd = statistics.stdev(times) if len(times) > 1 else 0.0
    res = {
        'meta': meta,
        'per_sample_seconds': times,
        'nfes_per_sample': nfes,
        'mean_s': mean,
        'sd_s': sd,
        'median_s': statistics.median(times),
        'min_s': min(times), 'max_s': max(times),
        'nfe_mean': statistics.mean(nfes) if nfes else None,
        'extrapolated_1000_s': mean * 1000,
        'extrapolated_1000_sd_s': sd * (1000 ** 0.5),  # sd of the SUM of 1000 draws
        'peak_mem_bytes': torch.cuda.max_memory_allocated(),
        'co_tenants_at_end': co_tenants(),
    }
    print(f'[RESULT] {args.strategy} k={k}: {mean:.3f} +- {sd:.3f} s/sample '
          f'over n={args.n}; NFE={res["nfe_mean"]}; '
          f'extrapolated 1000 = {mean*1000:.0f} s', flush=True)
    print(f'[info] co-tenants at end: {res["co_tenants_at_end"]}', flush=True)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, 'w') as f:
        json.dump(res, f, indent=2)
    print(f'[info] wrote {args.out}', flush=True)


if __name__ == '__main__':
    main()
